### ISSUE TITLE
Cursor is showing up

### ISSUE THREAD

**Issue by phelow** [phelow/KeyboardKommander#54]

**Comment by cloudhero01** [comment]
This has been an existing problem for a very long time and it still seems to be a problem even today:
https://forum.unity.com/threads/cursor-visible-not-working-5-0.307060/

It was a common conclusion for everyone that you needed to update the visibility every frame because something seems to reset it after the start.

I tested a variable declared outside the method, which I used to see if the cursor becomes visible after Update() being called just once, but the setting was never reset.  This leads me to believe something is overwriting Start().

Even more unusual, the first level seems to work fine with the standard method, but all other levels do not.  I've not seen any difference which would seemingly relate, so for now I'm making the cursor invisible in the update.  This will at least *guarantee* it stays invisible, even if it is not an efficient action to take.  This can be an improvement for later.
